SCREEN_WIDTH = 1200
SCREEN_HEIGHT = 750
BLOCK_WIDTH = 10
BLOCK_HEIGHT = 10
MAZE_WIDTH = int(SCREEN_WIDTH / BLOCK_WIDTH)
MAZE_HEIGHT = int(SCREEN_HEIGHT / BLOCK_HEIGHT)

OBSTACLE_CHANCE = 25  # percent
OBSTACLE_COLOR = (0, 0, 0)
BLANK_COLOR = (255, 255, 255)
PATH_COLOR = (0, 255, 0)
CURRENT_COLOR = (0, 150, 0)
START_COLOR = (255, 0, 0)
END_COLOR = (0, 0, 255)

OBSTACLE = "#"
BLANK = "_"
PATH = "*"
CURRENT = "-"
START = "("
END = ")"

COLORS_DICT = {OBSTACLE: OBSTACLE_COLOR, BLANK: BLANK_COLOR,
               PATH: PATH_COLOR, CURRENT: CURRENT_COLOR,
               START: START_COLOR, END: END_COLOR}
